### ISSUE TITLE
Option to exclude or ignore specific artifacts

### ISSUE THREAD

**Issue by Tim203** [rusterlium/rustler#503]
First of all, thank you for creating Rustler! I really enjoy using it.

I have a Cargo.toml that looks something like this:
```toml
[package]
name = "name"

[lib]
name = "name"
path = "src/lib.rs"
crate-type = ["cdylib"]

[[bin]]
name = "name-bin"
path = "src/main.rs"
required-features = ["build-binary"]
```

I use the lib artifact in my Elixir code, and I use the bin artifact to debug the lib with some GUI stuff that's not needed in the lib artifact (prevents fetching and compiling unneeded dependencies).

Once it has successfully compiled, Rustler tries to copy all artifacts:
```
** (File.CopyError) could not copy from "/app/_build/prod/lib/xx/native/name/release/name-bin" to "priv/native/name-bin": no such file or directory
    (elixir 1.14.0) lib/file.ex:838: File.cp!/3
    (elixir 1.14.0) lib/enum.ex:975: Enum."-each/2-lists^foreach/1-0-"/2
    (rustler 0.26.0) lib/rustler/compiler.ex:44: Rustler.Compiler.compile_crate/2
    ...
```
This is not desired because I only need the lib, which has successfully compiled.
Instead, my build failed because not every artifact was compiled.

Related Rustler code:
https://github.com/rusterlium/rustler/blob/rustler-0.26.0/rustler_mix/lib/rustler/compiler.ex#L178
https://github.com/rusterlium/rustler/blob/rustler-0.26.0/rustler_mix/lib/rustler/compiler.ex#L197

My personal preference would go to a solution like this: Continue to try to copy all possible artifacts, but give a warning instead of halting the Rustler compile process when a specific artifact doesn't exist (but maybe require at least one artifact per package?).
I'm also ok with a solution that allows people to exclude/include specific artifacts.
